name: fr-coverage
permissions:
  contents: read
  pull-requests: read
on: [pull_request]
jobs:
  fr:
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: echo "FR coverage check placeholder"
