name: Trufflehog Secrets Scan
on:
  push:
    branches: [main]
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
        with:
          fetch-depth: 0
      - uses: trufflehog/actions/setup@main
      - run: trufflehog github --only-verified --no-update
        env:
          GH_TOKEN: \${{ secrets.GITHUB_TOKEN }}
